export const ICON_PATH = 'assets/images/icons/';
export const ICONS = [
  'again',
  'arrow-down',
  'calendar',
  'check',
  'close',
  'cubes',
  'close-white',
  'delete',
  'edit',
  'email',
  'empty-user',
  'empty-user-v2',
  'hamburger-menu',
  'header-select-arrow',
  'location',
  'lock',
  'logo',
  'phone',
  'phone-v2',
  'search',
  'warning',
];
